db.url=jdbc:postgresql://localhost:5432/campus
db.user=campus
db.pass=campus
crypto.key=Rc4StaticKey#Campus2026
bot.webhook=http://localhost:5000/review
bot.token=lab-bot-token-890d7ba8d41377626cceaa03f0ab67f1b245d8b6e57d156f66a0e7092b62f3cf
